'use strict';
const S=window.FOREST_SAMPLE, $=s=>document.querySelector(s), canvas=$('#film'), ctx=canvas.getContext('2d'), voice=$('#voice');
const W=1920,H=1080,accent='#c7dca1',names=['A second layer of life','A community in fallen wood','The nurse log','Read the forest'];
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,ready=false,recording=false,recorder=null,recordStream=null,audioCtx=null,destination=null,sourceNode=null,downloadURL=null,lastCue=-1;
const images=new Map(),fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const duration=()=>Number.isFinite(voice.duration)?voice.duration:S.duration;
const status=t=>{$('#status').textContent=t};
function text(t,x,y,size=24,color='#e7ecdf',font='Segoe UI',align='left'){ctx.font=`${size}px ${font}`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(t,x,y)}
function wrap(t,x,y,width,size=35,line=48){ctx.font=`${size}px Georgia`;ctx.textAlign='left';ctx.fillStyle='#e7ecdf';let row='',n=0;for(const word of t.split(' ')){let next=row?row+' '+word:word;if(ctx.measureText(next).width>width&&row){ctx.fillText(row,x,y+n*line);n++;row=word}else row=next}ctx.fillText(row,x,y+n*line);return n+1}
function line(ps,color,width=1){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ps.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke()}
function orb(t){const R=229,cx=316,cy=457,turns=2.15,u=Math.min(1,t/2.2),ease=u*u*(3-2*u);const yaw=-2/7*Math.PI*2*turns-(Math.PI*2*turns/7)*ease+(motion?Math.sin(t/8)*.12:0);
const xyz=q=>{let lat=(.43-.86*q)*Math.PI,lon=q*Math.PI*2*turns;return [Math.cos(lat)*Math.sin(lon),-Math.sin(lat),Math.cos(lat)*Math.cos(lon)]};
const proj=v=>{let[x,y,z]=v;return[cx+(x*Math.cos(yaw)+z*Math.sin(yaw))*R,cy+y*R,z*Math.cos(yaw)-x*Math.sin(yaw)]};
let glow=ctx.createRadialGradient(cx-60,cy-75,15,cx,cy,R);glow.addColorStop(0,'#315956');glow.addColorStop(1,'#0b242a');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();
for(let lat=-75;lat<=75;lat+=15){let ps=[];for(let lon=0;lon<=360;lon+=3){let a=lat*Math.PI/180,b=lon*Math.PI/180,p=proj([Math.cos(a)*Math.sin(b),-Math.sin(a),Math.cos(a)*Math.cos(b)]);if(p[2]>0)ps.push(p.slice(0,2));else if(ps.length){line(ps,'#71958a35');ps=[]}}if(ps.length)line(ps,'#71958a35')}
let prev=null;for(let n=0;n<=360;n++){const p=proj(xyz(n/360));if(prev)line([prev.slice(0,2),p.slice(0,2)],p[2]>0?'#c7dca1b0':'#69885740',p[2]>0?2.3:1.4);prev=p}
const ns=Array.from({length:8},(_,i)=>({i,p:proj(xyz(i/7))})).sort((a,b)=>a.p[2]-b.p[2]);for(const {i,p:[x,y,z]} of ns){const active=i===3;ctx.globalAlpha=active?1:z<0?.5:1;if(active){ctx.beginPath();ctx.arc(x,y,34+(motion?Math.sin(t*2)*2:0),0,Math.PI*2);ctx.strokeStyle='#c7dca177';ctx.lineWidth=2;ctx.stroke()}ctx.beginPath();ctx.arc(x,y,active?23:16,0,Math.PI*2);ctx.fillStyle=active?accent:'#123132';ctx.fill();ctx.strokeStyle='#8ba794';ctx.stroke();text(String(i+1),x,y+7,active?23:18,active?'#122822':'#d7e3d3','Segoe UI','center')}ctx.globalAlpha=1;
text('04 / 08',cx,745,23,accent,'Segoe UI','center');text('THE LIVING FOREST',cx,788,23,'#c5d5c9','Segoe UI','center');text('One point in a connected valley',cx,824,20,'#8da89e','Segoe UI','center');}
function schematic(i){let x=658,y=170,w=1198,h=580;ctx.fillStyle='#102d30';ctx.fillRect(x,y,w,h);ctx.save();ctx.translate(x,y);line([[90,432],[315,408],[590,416],[1060,431]],'#a78c62',48);const count=i===0?2:5;for(let n=0;n<count;n++){let bx=230+n*158,by=415,top=160+(n%3)*28;line([[bx,by],[bx,top]],accent,5);line([[bx-42,top+70],[bx,top],[bx+42,top+70]],accent,4);if(i>=2){line([[bx,by],[bx-25,480]],'#92aa7c',4);line([[bx,by],[bx+30,480]],'#92aa7c',4)}}text('FALLEN WOOD  →  NEW GROWTH',599,82,30,accent,'Segoe UI','center');text('Explanatory illustration · not a photograph',599,544,22,'#a2b7ad','Segoe UI','center');ctx.restore()}
function photo(cue,t,alpha=1){const im=images.get(cue.asset);if(!im){schematic(S.cues.indexOf(cue));return}const x=658,y=170,w=1198,h=580;let frac=Math.max(0,Math.min(1,(t-cue.start)/Math.max(1,cue.end-cue.start)));const zoom=motion?1+.035*frac:1;const scale=Math.max(w/im.width,h/im.height)*zoom;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.globalAlpha*=alpha;ctx.drawImage(im,x+(w-im.width*scale)/2,y+(h-im.height*scale)*(cue.focus?.[1]??.5),im.width*scale,im.height*scale);ctx.restore()}
function render(){const t=voice.currentTime||0;let k=Math.max(0,S.cues.findLastIndex(c=>c.start<=t+.001)),cue=S.cues[k];ctx.fillStyle='#091f24';ctx.fillRect(0,0,W,H);text('QUINAULT',64,83,51,'#f0eee1','Georgia');text('ORB  /  FIELD FILM 01',1856,76,22,accent,'Segoe UI','right');line([[64,115],[1856,115]],'#34514b');text('A forest grows through decay',658,143,26,'#d6e0d1','Georgia');orb(motion?t:3);photo(cue,t);if(motion&&k>0&&t-cue.start<.65){ctx.save();ctx.globalAlpha=1-(t-cue.start)/.65;photo(S.cues[k-1],t);ctx.restore()}text(cue.caption,658,788,22,'#b2c5b9');text(cue.asset?'NATHAN WILSON / PERSONAL PHOTOGRAPHS':'EXPLANATORY ILLUSTRATION',658,825,18,'#90aa9f');line([[64,864],[1856,864]],'#35524b');wrap(cue.text,64,916,1792,34,47);ctx.fillStyle='#38564a';ctx.fillRect(64,1040,1792,3);ctx.fillStyle=accent;ctx.fillRect(64,1040,1792*Math.min(1,t/duration()),3);
$('#clock').textContent=`${fmt(t)} / ${fmt(duration())}`;$('#seek').value=t;$('#seek').max=duration();if(k!==lastCue){lastCue=k;document.querySelectorAll('[data-cue]').forEach((b,i)=>b.setAttribute('aria-current',String(i===k)));canvas.setAttribute('aria-label',`Quinault: ${names[k]}. ${cue.caption}. ${cue.text}`)}requestAnimationFrame(render)}
function transport(){ $('#play').textContent=voice.paused?(voice.ended?'Replay study':'Play study'):'Pause';$('#motion').textContent=motion?'Motion on':'Motion off';$('#motion').setAttribute('aria-pressed',String(motion)); }
async function start(){try{if(voice.ended)voice.currentTime=0;if(audioCtx)await audioCtx.resume();await voice.play();status('Playing the forest study.')}catch(e){status('Playback could not start: '+e.message)}}
$('#play').onclick=()=>voice.paused?start():voice.pause();$('#seek').oninput=e=>{voice.currentTime=Number(e.target.value)};$('#motion').onclick=()=>{motion=!motion;transport()};voice.addEventListener('play',transport);voice.addEventListener('pause',transport);voice.addEventListener('error',()=>status('Narration unavailable. Check the accompanying audio file.'));
$('#passages').innerHTML=names.map((n,i)=>`<button data-cue="${i}">${String(i+1).padStart(2,'0')} / ${n}</button>`).join('');$('#passages').onclick=e=>{const b=e.target.closest('[data-cue]');if(b&&!recording)voice.currentTime=S.cues[Number(b.dataset.cue)].start};S.passages.forEach(p=>{let el=document.createElement('p');el.textContent=p;$('#transcript').append(el)});$('#credits').textContent=S.credits;
$('#print').onclick=()=>{voice.pause();window.print()};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|BUTTON/.test(e.target.tagName)&&!recording){e.preventDefault();$('#play').click()}});
function lock(on){recording=on;for(const el of document.querySelectorAll('#play,#seek,#motion,#passages button,#print'))el.disabled=on;$('#record').disabled=on||!ready;}
async function record(){if(!ready||recording)return;let chunks=[];try{voice.pause();voice.currentTime=0;if(!audioCtx){audioCtx=new AudioContext();sourceNode=audioCtx.createMediaElementSource(voice);destination=audioCtx.createMediaStreamDestination();sourceNode.connect(destination);sourceNode.connect(audioCtx.destination)}await audioCtx.resume();let visual=canvas.captureStream(30);recordStream=new MediaStream([...visual.getVideoTracks(),...destination.stream.getAudioTracks()]);let mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('This browser cannot record WebM.');recorder=new MediaRecorder(recordStream,{mimeType:mime,videoBitsPerSecond:7000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=e=>{status('Recording failed. Please retry.');lock(false)};recorder.onstop=async()=>{recordStream.getVideoTracks().forEach(t=>t.stop());lock(false);const blob=new Blob(chunks,{type:mime});if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=URL.createObjectURL(blob);const a=$('#download');a.href=downloadURL;a.download='Quinault-Forest-Study.webm';a.hidden=false;a.textContent='Download recorded tour (WebM)';status('Recording complete. Download the tour below.');if(location.hostname==='127.0.0.1'&&location.port==='8766'){try{const r=await fetch('/__recording',{method:'POST',headers:{'Content-Type':'video/webm'},body:blob});if(!r.ok)throw Error('Save failed');status('Recording saved locally. Ready for MP4 conversion.')}catch(e){status('Recording ready; use Download recorded tour to save it.')}}};lock(true);recorder.start(1000);await voice.play();status('Recording the complete tour with narration. Keep this page visible until it finishes.')}catch(e){if(recorder?.state==='recording')recorder.stop();lock(false);status('Could not record: '+e.message)}}
$('#record').onclick=record;voice.addEventListener('ended',()=>{transport();if(recorder?.state==='recording'){setTimeout(()=>recorder.stop(),350)}else status('Study complete. Replay or explore the full Quinault ORB.')});
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){motion=false;transport()}});
Promise.all(S.cues.filter(c=>c.asset).map(c=>new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{images.set(c.asset,im);resolve()};im.onerror=()=>reject(Error('A photograph could not load'));im.src=c.asset}))).then(()=>{if(voice.readyState>=2)loaded();else voice.addEventListener('canplay',loaded,{once:true})}).catch(e=>status(e.message));function loaded(){ready=true;$('#play').disabled=false;$('#record').disabled=!(canvas.captureStream&&window.MediaRecorder);status('Ready · '+fmt(S.duration)+' narrated study. Record this tour saves its playback as WebM.');transport()}transport();render();
